### ISSUE TITLE
webhook and project wildcards

### ISSUE THREAD

**Issue by prudnitskiy** [mvisonneau/gitlab-ci-pipelines-exporter#158] opened 2020-10-16 08:44 UTC
As far as I can see now -- it is required to have project configured if webhook enabled. In case I have a lot of projects and webhook enabled for all of them -- I need to write all of them down in config. Project discovery via wildcards will not work (webhook will be ignored even if the project was successfully discovered). Is there any workaround to fix it?

**Comment by mvisonneau** [comment] 2020-10-16 09:13
👋 hey @prudnitskiy, webhooks should be working on projects discovered through wildcards, isn't it the case? 🤔

**Comment by mvisonneau** [comment] 2020-10-22 08:58
I am using it in push mode with wildcards myself and it seems to be working finely. Can you share a sanitized version of your config please?

**Comment by mvisonneau** [comment] 2021-01-25 14:14
I haven't been able to reproduce your issue, I will close it for now, feel free to reopen if necessary 👍

**Closed by mvisonneau** 2021-01-25 14:14 UTC
Labels: question
