### ISSUE TITLE
Queue buffer size too small 

### ISSUE THREAD

**Issue by enzeperix** [mvisonneau/gitlab-ci-pipelines-exporter#561] opened 2022-11-15 23:51 UTC
Hello. I keep getting thousands of warnings like this  :
time="2022-11-15T23:43:04Z" level=warning msg="queue buffer size exhausted, skipping scheduling of task.." task_type=PullRefMetrics task_unique_id=1021928646

It seems that the issue is the value of this var from /pkg/controller/scheduler.go, line 21  :
const bufferSize = 1000 

Is it enough to modify it and recompile the code ? If increased to 10000  does it have a bad impact besides more memory usage ?

**Comment by DurgeshBarve** [comment] 2023-01-06 09:58
Do you got the solution for it?

**Comment by mikaello** [comment] 2023-01-22 07:13
Duplicate of https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/327, @mvisonneau has some suggestions here: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/327#issuecomment-1171415537

**Comment by mvisonneau** [comment] 2023-05-22 10:06
in case you really need it, I've added a [new configuration parameter](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/90444f156508db4457a4025dcd7851a63ec5aaa8#diff-4194838c0fad9762c5a0e565dd61998e713f6710b58d5d8bd6bf19005ab589caR97-R106) (available from [v0.5.5](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/releases/tag/v0.5.5))

**Closed by mvisonneau** 2023-05-22 10:06 UTC
