### ISSUE TITLE
Token not being fetched correctly

### ISSUE THREAD

**Issue by joao-p-marques** [mvisonneau/gitlab-ci-pipelines-exporter#113] opened 2020-06-02 11:25 UTC
When I try to setup the application using docker and the config file:
```
config:
  gitlab:
    url: https://gitlab.com
    token: <MY_TOKEN>
```
The app does not work, and returns a 404 when trying to fetch data from GitLab API (same error as when the token is wrong).

However, if I pass the same token through the command line:
```
docker run -d --name gitlab-ci-pipelines-exporter -v $(pwd)/gitlab-ci-pipelines-exporter/config.yml:/etc/config.yml -p 8888:8080 mvisonneau/gitlab-ci-pipelines-exporter:latest --config /etc/config.yml --gitlab-token <MY_TOKEN>
```
It works as expected.

Why is the token not being fetched correctly? Am I doing the config wrong?

**Comment by xt99** [comment] 2020-06-03 10:58
Same thing for me also

**Comment by mvisonneau** [comment] 2020-06-03 13:05
:wave: I tried to reproduce the bug using the `master` branch and I was not able to.
Which versions are you using @joao-p-marques @xt99 ? 🤔

**Comment by mvisonneau** [comment] 2020-06-03 13:07
Have you got any special characters that could be misinterpolated from yaml?
To double check, the `<` `>` are not expected in the syntax:

```yaml
gitlab:
  url: https://gitlab.com
  token: 'XxXxXxxxXxxXxx'
```

**Comment by xt99** [comment] 2020-06-03 13:21
I've used the latest tagged version – `0.3.2`. 
My token has only letters (lowercased and uppercased) and numbers. No other symbols. Once I've moved token to env var – 404 error disappeared and scanning of the repos in my group started.

**Comment by mvisonneau** [comment] 2020-06-03 13:23
hmm interesting, have you tested with single quotes around your token as well?

**Comment by joao-p-marques** [comment] 2020-06-03 13:28
👋 Same here. I am using the latest image version, and also tried wrapping the token in double quotes, which should be the same in YAML right?
As for the token, the only "strange" characters it has are `_`

**Comment by mvisonneau** [comment] 2020-06-03 13:41
I pushed 9606236, which should not fix your issue but at least will throw a more explicit error than the 404 if the token is presumably not set.

**Comment by joao-p-marques** [comment] 2020-06-03 13:42
Ok, thanks! :+1: 
Indeed, I took me some time to realize the problem was the missing token inside the container, so this should help for now!

**Comment by mvisonneau** [comment] 2020-10-06 16:55
Looking at this issue again, I reckon could be due to the `config` in your config.yml file. As I did not manage to reproduce it otherwise I will close this issue! Feel free to reopen if this is still problematic with the most recent versions of the tool.

**Closed by mvisonneau** 2020-10-06 16:55 UTC
Labels: bug
